# -*- coding: utf-8 -*-
"""yolov7_face.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13O6WjJzS7X_ST5zZUBoTXOIgjQcqJ7Ex
"""

!nvidia-smi

!git clone https://github.com/WongKinYiu/yolov7

# Commented out IPython magic to ensure Python compatibility.
# %cd /content

pwd

!pip install unzip

!unzip /content/face_yolov7.zip -d /content/

!rm /content/face_yolov7.zip

cd yolov7

pwd

!pip install -r requirements.txt

import os

train_img_path = "/content/images/train"
val_img_path = "/content/images/val"

# Commented out IPython magic to ensure Python compatibility.
# %cd /content

pwd

with open("train.txt", "a+") as f:
  img_list = os.listdir(train_img_path)
  for img in img_list:
    f.write(os.path.join(train_img_path,img+'\n'))
  print('Done')

with open('train.txt', 'r') as file:
    contents = file.read()
    print(contents)

with open("val.txt", "a+") as f:
  img_list = os.listdir(val_img_path)
  for img in img_list:
    f.write(os.path.join(val_img_path,img+'\n'))
  print('Done')

with open('val.txt', 'r') as file:
    contents = file.read()
    print(contents)

# Commented out IPython magic to ensure Python compatibility.
# %cp /content/yolov7/data/coco.yaml /content/yolov7/data/face.yaml

!pip install wget

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/yolov7

pwd

!wget https://github.com/WongKinYiu/yolov7/releases/download/v0.1/yolov7.pt

# Commented out IPython magic to ensure Python compatibility.
# %cp /content/yolov7/cfg/training/yolov7.yaml /content/yolov7/cfg/training/face_yolov7.yaml

pwd

!python train.py --device 0 --epochs 100 --batch-size 16 --data data/face.yaml --img 640 640 --cfg cfg/training/face_yolov7.yaml --weights 'yolov7.pt'

!pip install ipython

from IPython.display import Image
Image(filename='/content/classroom.png')

!python detect.py --weights /content/yolov7/runs/train/exp/weights/best.pt --source /content/classroom.png

Image(filename='/content/yolov7/runs/detect/exp/classroom.png')

!python person_face_detect.py --weights /content/yolov7/runs/train/exp/weights/best.pt --source /content/classroom.png

Image(filename='/content/yolov7/runs/detect/exp_0/classroom.png')